### ISSUE TITLE
When location permissions are restricted, entire app lags and navBar becomes unresponsive

### ISSUE THREAD

**Issue by lh1207** [lh1207/LocoQuest#31]
I/ViewRootImpl@1a3c2d9[MainActivity]: performTraversals params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030309
      fl=81810100
      pfl=12020040
      bhv=DEFAULT
      fitSides= naviIconColor=0}
I/ViewRootImpl@1a3c2d9[MainActivity]: performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030309
      fl=81810100
      pfl=12020040
      bhv=DEFAULT
      fitSides= naviIconColor=0}
I/ViewRootImpl@1a3c2d9[MainActivity]: updateBlastSurfaceIfNeeded mBlastBufferQueue=0xb400007992763200 isSameSurfaceControl=true
I/BLASTBufferQueue: update, w= 1080 h= 2400 mName = ViewRootImpl@1a3c2d9[MainActivity] mNativeObject= 0xb400007992763200 sc.mNativeObject= 0xb400007a23b817c0 format= -1 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2898 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 
I/ViewRootImpl@1a3c2d9[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=6 res=0x0 s={true 0xb4000079b7bce800} ch=false seqId=0
I/ViewRootImpl@1a3c2d9[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 0
I/ViewRootImpl@1a3c2d9[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 0
I/ViewRootImpl@1a3c2d9[MainActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000079b7bce800}
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@1a3c2d9[MainActivity]: ViewPostIme pointer 0
W/Activity: Can request only one set of permissions at a time

**Comment by derrickadkins** [comment]
the commit e4a20bd5808e3bb3b12a7bfc219ad5b0603129cf resolved the issue
